trigger:
- none

pool:
  vmImage: 'latest'

variables:
  imageName: 'dvwa'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
